source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem 'wdm', '>= 0.1.0' if Gem.win_platform?

# Required for Ruby 3.4+ (removed from stdlib)
gem "erb"
gem "csv"
gem "base64"
gem "bigdecimal"